-   id: requirements-txt-sorter
    name: Fix requirements.txt
    description: Sorts entries in requirements.txt
    entry: requirements-txt-sorter
    language: python
    files: requirements.*\.txt$
